//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ChangeLog
    {
        public string TableName { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public System.Guid ChangeLogID { get; set; }
    }
}
